Update environment.yml
Pinning to pyhton 3.7 because 3.6 gives `AttributeError: module 'asyncio' has no attribute 'get_running_loop'` (see https://stackoverflow.com/questions/52796630/python3-6-attributeerror-module-asyncio-has-no-attribute-run)